[build]
  # La ruta del directorio a publicar después de la construcción
  publish = "/"
  # El comando para ejecutar el servidor de la aplicación
  command = "pip install -r requirements.txt && gunicorn app:app"

[context.production.environment]
  # Establece la variable de entorno para Gunicorn (opcional)
  GUNICORN_CMD_ARGS = "--bind 0.0.0.0 --workers 4"
