[build]
  ##command = "pip install -r requirements.txt && gunicorn app:app"
  command = "pip install -r requirements.txt && python app.py"
  publish = "/"

[context.production.environment]
  GUNICORN_CMD_ARGS = "--bind 0.0.0.0 --workers 1"
